# -*- coding: utf-8 -*-
"""startup ideas ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeoEaVoXcMDMki1Lu2LyHe4UrjSxIWV0
"""

import gradio as gr
from groq import Groq
import os

# Global variable to store the Groq client
groq_client = None
api_key_verified = False

def verify_api_key(api_key):
    """Verify if the provided API key is valid"""
    global groq_client, api_key_verified

    if not api_key or api_key.strip() == "":
        return "❌ Please enter an API key", ""

    try:
        # Initialize Groq client
        groq_client = Groq(api_key=api_key.strip())

        # Test the API key with a simple request
        response = groq_client.chat.completions.create(
            messages=[{"role": "user", "content": "Hi"}],
            model="llama-3.3-70b-versatile",
            max_tokens=10
        )

        api_key_verified = True
        return "✅ API Key verified successfully! You can now start chatting.", api_key

    except Exception as e:
        api_key_verified = False
        groq_client = None
        return f"❌ API Key verification failed: {str(e)}", ""

def is_startup_related(message):
    """Check if the message is related to startup ideas"""
    startup_keywords = [
        'startup', 'business', 'idea', 'venture', 'entrepreneur', 'company',
        'market', 'product', 'service', 'customer', 'revenue', 'monetize',
        'funding', 'investor', 'pitch', 'mvp', 'prototype', 'launch',
        'competition', 'competitor', 'niche', 'target audience', 'marketing',
        'sales', 'growth', 'scale', 'business model', 'value proposition',
        'problem', 'solution', 'innovation', 'disrupt', 'industry'
    ]

    message_lower = message.lower()
    return any(keyword in message_lower for keyword in startup_keywords)

def chat_with_mentor(message, history, api_key):
    """Main chat function for the startup mentor"""
    global groq_client, api_key_verified

    # Check if API key is verified
    if not api_key_verified or not groq_client:
        history.append((message, "⚠️ Please verify your API key first using the 'Verify API Key' button above."))
        return history

    # Check if message is empty
    if not message or message.strip() == "":
        history.append((message, "Please enter a message."))
        return history

    # Check if the question is startup-related
    if not is_startup_related(message):
        history.append((message, "🚫 I'm a startup idea mentor and can only help with startup-related questions. Please ask me about business ideas, entrepreneurship, market analysis, product development, or anything related to building a startup!"))
        return history

    try:
        # Build conversation history for context
        messages = [
            {
                "role": "system",
                "content": """You are an expert startup idea mentor with deep knowledge in entrepreneurship, business strategy, and innovation. Your role is to:

1. Help entrepreneurs brainstorm and validate startup ideas
2. Provide insights on market analysis and competitor research
3. Assist with business model development
4. Offer guidance on product-market fit
5. Share advice on funding, pitching, and scaling
6. Challenge ideas constructively and ask thought-provoking questions

Be encouraging yet realistic. Ask clarifying questions when needed. Provide actionable advice and real-world examples. Keep responses concise but valuable."""
            }
        ]

        # Add conversation history
        for user_msg, assistant_msg in history:
            messages.append({"role": "user", "content": user_msg})
            messages.append({"role": "assistant", "content": assistant_msg})

        # Add current message
        messages.append({"role": "user", "content": message})

        # Get response from Groq
        response = groq_client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            max_tokens=1500,
            temperature=0.7
        )

        bot_response = response.choices[0].message.content
        history.append((message, bot_response))
        return history

    except Exception as e:
        error_msg = f"❌ Error: {str(e)}\n\nPlease check your API key and try again."
        history.append((message, error_msg))
        return history

# Create Gradio interface
with gr.Blocks(theme=gr.themes.Soft(), title="Startup Ideas Mentor") as demo:
    gr.Markdown(
        """
        # 🚀 Startup Ideas Mentor
        ### Your AI-powered entrepreneurship advisor

        Get expert guidance on startup ideas, business strategy, market analysis, and more!
        """
    )

    with gr.Row():
        with gr.Column(scale=3):
            api_key_input = gr.Textbox(
                label="Groq API Key",
                placeholder="Enter your Groq API key here...",
                type="password"
            )
        with gr.Column(scale=1):
            verify_btn = gr.Button("🔑 Verify API Key", variant="primary")

    api_status = gr.Textbox(label="Status", interactive=False)
    verified_key = gr.State("")

    gr.Markdown("---")

    chatbot = gr.Chatbot(
        height=450,
        label="Chat with your Startup Mentor",
        bubble_full_width=False
    )

    with gr.Row():
        msg = gr.Textbox(
            label="Your Question",
            placeholder="Ask me anything about startups, business ideas, entrepreneurship...",
            scale=4
        )
        submit = gr.Button("Send 📤", scale=1, variant="primary")

    gr.Markdown(
        """
        ### 💡 Example Questions:
        - I have an idea for a SaaS platform targeting small businesses. How do I validate it?
        - What are the key metrics I should track for my e-commerce startup?
        - How can I differentiate my product in a crowded market?
        - What should I include in my pitch deck for investors?
        """
    )

    # Button click handlers
    verify_btn.click(
        fn=verify_api_key,
        inputs=[api_key_input],
        outputs=[api_status, verified_key]
    )

    submit.click(
        fn=chat_with_mentor,
        inputs=[msg, chatbot, verified_key],
        outputs=[chatbot]
    ).then(
        lambda: "",
        None,
        [msg]
    )

    msg.submit(
        fn=chat_with_mentor,
        inputs=[msg, chatbot, verified_key],
        outputs=[chatbot]
    ).then(
        lambda: "",
        None,
        [msg]
    )

# Launch the app
if __name__ == "__main__":
    demo.launch(share=True)